import type { DashboardData } from "./types";

export const mockData: DashboardData = {
  overview: {
    total_windows: 6,
    normal_windows: 1,
    anomaly_windows: 5,
    anomaly_rate: 0.833,
    sensor_count: 6,
    process_step_count: 4,
    top_weak_fault_category: "RF_MATCHING_ABNORMAL",
    top_anomalous_sensor: "RF_REFLECTED_POWER",
    random_forest: {
      model: "Random Forest",
      accuracy: 0.982,
      precision: 0.913,
      recall: 0.887,
      f1: 0.9,
      roc_auc: 0.971
    },
    isolation_forest: {
      model: "Isolation Forest",
      accuracy: 0.943,
      precision: 0.642,
      recall: 0.701,
      f1: 0.67,
      roc_auc: 0.824
    },
    anomaly_by_step: [
      { process_step: "ETCH_STABILIZE", anomaly_windows: 2 },
      { process_step: "LOAD_LOCK_PUMP", anomaly_windows: 1 },
      { process_step: "TEMP_RAMP", anomaly_windows: 1 },
      { process_step: "TRANSFER", anomaly_windows: 1 }
    ],
    anomaly_by_sensor: [
      { sensor_name: "RF_REFLECTED_POWER", anomaly_windows: 1 },
      { sensor_name: "RF_FORWARD_POWER", anomaly_windows: 1 },
      { sensor_name: "LOAD_LOCK_PRESSURE", anomaly_windows: 1 },
      { sensor_name: "HEATER_ZONE_3_TEMP", anomaly_windows: 1 },
      { sensor_name: "ROBOT_TRANSFER_TIME", anomaly_windows: 1 }
    ]
  },
  windows: [
    {
      window_start: "2026-07-08T09:00:00",
      window_end: "2026-07-08T09:05:00",
      process_step: "ETCH_STABILIZE",
      sensor_name: "RF_FORWARD_POWER",
      window_n: 300,
      window_mean: 524.2,
      window_std: 18.7,
      window_min: 491,
      window_max: 563.8,
      window_slope: 0.18,
      baseline_mean: 498.4,
      baseline_std: 7.2,
      z_score: 3.58,
      lower_3sigma: 476.8,
      upper_3sigma: 520,
      iqr_lower_bound: 481.6,
      iqr_upper_bound: 516.2,
      is_3sigma_outlier: 1,
      is_iqr_outlier: 1,
      ewma_flag: 1,
      cusum_flag: 0,
      target_anomaly: 1,
      weak_fault_category: "RF_MATCHING_ABNORMAL",
      weak_fault_confidence: 0.76,
      rationale: "RF power mean exceeded the step baseline and crossed 3-sigma/IQR limits."
    },
    {
      window_start: "2026-07-08T09:05:00",
      window_end: "2026-07-08T09:10:00",
      process_step: "ETCH_STABILIZE",
      sensor_name: "CHAMBER_PRESSURE",
      window_n: 300,
      window_mean: 38.6,
      window_std: 1.2,
      window_min: 36.9,
      window_max: 42.8,
      window_slope: 0.03,
      baseline_mean: 38.2,
      baseline_std: 0.9,
      z_score: 0.44,
      lower_3sigma: 35.5,
      upper_3sigma: 40.9,
      iqr_lower_bound: 36.1,
      iqr_upper_bound: 40.6,
      is_3sigma_outlier: 0,
      is_iqr_outlier: 0,
      ewma_flag: 0,
      cusum_flag: 0,
      target_anomaly: 0,
      weak_fault_category: "NORMAL",
      weak_fault_confidence: 0.91,
      rationale: "Window stayed within expected control limits for this process step."
    },
    {
      window_start: "2026-07-08T09:10:00",
      window_end: "2026-07-08T09:15:00",
      process_step: "LOAD_LOCK_PUMP",
      sensor_name: "LOAD_LOCK_PRESSURE",
      window_n: 300,
      window_mean: 12.8,
      window_std: 4.1,
      window_min: 7.4,
      window_max: 21.6,
      window_slope: -0.07,
      baseline_mean: 6.2,
      baseline_std: 1.5,
      z_score: 4.4,
      lower_3sigma: 1.7,
      upper_3sigma: 10.7,
      iqr_lower_bound: 2.8,
      iqr_upper_bound: 9.6,
      is_3sigma_outlier: 1,
      is_iqr_outlier: 1,
      ewma_flag: 0,
      cusum_flag: 1,
      target_anomaly: 1,
      weak_fault_category: "LOAD_LOCK_PUMP_DOWN_SLOW",
      weak_fault_confidence: 0.82,
      rationale: "Pressure remained elevated during pump-down and triggered 3-sigma, IQR, and CUSUM evidence."
    },
    {
      window_start: "2026-07-08T09:15:00",
      window_end: "2026-07-08T09:20:00",
      process_step: "TEMP_RAMP",
      sensor_name: "HEATER_ZONE_3_TEMP",
      window_n: 300,
      window_mean: 222.5,
      window_std: 5.6,
      window_min: 211.7,
      window_max: 231.9,
      window_slope: 0.24,
      baseline_mean: 213.9,
      baseline_std: 2.6,
      z_score: 3.31,
      lower_3sigma: 206.1,
      upper_3sigma: 221.7,
      iqr_lower_bound: 207.5,
      iqr_upper_bound: 220.8,
      is_3sigma_outlier: 1,
      is_iqr_outlier: 1,
      ewma_flag: 1,
      cusum_flag: 1,
      target_anomaly: 1,
      weak_fault_category: "TEMPERATURE_CONTROL_DRIFT",
      weak_fault_confidence: 0.79,
      rationale: "Heater temperature trended above its process-step baseline with sustained EWMA/CUSUM flags."
    },
    {
      window_start: "2026-07-08T09:20:00",
      window_end: "2026-07-08T09:25:00",
      process_step: "TRANSFER",
      sensor_name: "ROBOT_TRANSFER_TIME",
      window_n: 300,
      window_mean: 8.9,
      window_std: 0.7,
      window_min: 7.8,
      window_max: 10.6,
      window_slope: 0.01,
      baseline_mean: 6.5,
      baseline_std: 0.8,
      z_score: 3,
      lower_3sigma: 4.1,
      upper_3sigma: 8.9,
      iqr_lower_bound: 4.9,
      iqr_upper_bound: 8.2,
      is_3sigma_outlier: 1,
      is_iqr_outlier: 1,
      ewma_flag: 0,
      cusum_flag: 0,
      target_anomaly: 1,
      weak_fault_category: "ROBOT_TRANSFER_DELAY",
      weak_fault_confidence: 0.68,
      rationale: "Transfer duration exceeded historical limits for the transfer step."
    },
    {
      window_start: "2026-07-08T09:25:00",
      window_end: "2026-07-08T09:30:00",
      process_step: "ETCH_STABILIZE",
      sensor_name: "RF_REFLECTED_POWER",
      window_n: 300,
      window_mean: 44.8,
      window_std: 9.1,
      window_min: 27.6,
      window_max: 63.4,
      window_slope: 0.11,
      baseline_mean: 29.5,
      baseline_std: 4.3,
      z_score: 3.56,
      lower_3sigma: 16.6,
      upper_3sigma: 42.4,
      iqr_lower_bound: 18.2,
      iqr_upper_bound: 40.9,
      is_3sigma_outlier: 1,
      is_iqr_outlier: 1,
      ewma_flag: 1,
      cusum_flag: 1,
      target_anomaly: 1,
      weak_fault_category: "RF_MATCHING_ABNORMAL",
      weak_fault_confidence: 0.84,
      rationale: "Reflected RF power was high and persisted across EWMA/CUSUM evidence."
    }
  ],
  fault_summary: [
    { weak_fault_category: "RF_MATCHING_ABNORMAL", window_count: 2 },
    { weak_fault_category: "LOAD_LOCK_PUMP_DOWN_SLOW", window_count: 1 },
    { weak_fault_category: "TEMPERATURE_CONTROL_DRIFT", window_count: 1 },
    { weak_fault_category: "ROBOT_TRANSFER_DELAY", window_count: 1 },
    { weak_fault_category: "NORMAL", window_count: 1 }
  ],
  model_comparison: [
    { model: "Random Forest", accuracy: 0.982, precision: 0.913, recall: 0.887, f1: 0.9, roc_auc: 0.971 },
    { model: "Logistic Regression", accuracy: 0.954, precision: 0.842, recall: 0.801, f1: 0.821, roc_auc: 0.918 },
    { model: "Isolation Forest", accuracy: 0.943, precision: 0.642, recall: 0.701, f1: 0.67, roc_auc: 0.824 },
    { model: "Local Outlier Factor", accuracy: 0.931, precision: 0.611, recall: 0.664, f1: 0.636, roc_auc: 0.802 },
    { model: "Autoencoder-style MLP", accuracy: 0.936, precision: 0.689, recall: 0.647, f1: 0.667, roc_auc: 0.837 }
  ],
  feature_importance: [
    { feature: "window_slope", importance: 0.152 },
    { feature: "window_std", importance: 0.131 },
    { feature: "window_range", importance: 0.119 },
    { feature: "setpoint_error_abs", importance: 0.104 },
    { feature: "oscillation_index", importance: 0.098 },
    { feature: "prev_window_trend", importance: 0.087 },
    { feature: "process_step_encoded", importance: 0.064 }
  ],
  metrics: {},
  files: [
    { name: "spc_targets/window_features_with_targets.csv", exists: false },
    { name: "ml_baselines/model_comparison.csv", exists: false },
    { name: "fault_statistics/weak_fault_summary.csv", exists: false },
    { name: "fault_statistics/weak_fault_windows.csv", exists: false }
  ],
  plot_files: [
    {
      id: "sample-swimlane",
      group: "Architecture",
      name: "fdc_process_swimlane.png",
      title: "FDC Process Swimlane",
      url: "/fdc-process-swimlane.png"
    }
  ]
};
